import { AssetRow } from '../urban-issue/types';

// src/features/assets/mockData.ts
export const MOCK_ASSETS: AssetRow[] = [
  {
    id: "a-001",
    name: "경복궁_근정전",
    bundleKey: "gyeongbokgung/geunjeongjeon@1",
    version: "1.0.1",
    category: "building",
    sizeMB: 186.2,
    updatedAt: "2025-09-11T10:30:00Z",
    status: "published",
    usage: "historical",
    tags: ["palace", "main-hall", "lod2"],
    locations: 7,
  },
  {
    id: "a-002",
    name: "경복궁_연못",
    bundleKey: "gyeongbokgung/pond@3",
    version: "1.3.0",
    category: "pond",
    sizeMB: 92.5,
    updatedAt: "2025-09-12T04:12:00Z",
    status: "published",
    usage: "both",
    tags: ["water", "reflection", "lod1"],
    locations: 5,
  },
  {
    id: "a-003",
    name: "브랜드_포토월_2025",
    bundleKey: "promo/photowall@2025",
    version: "2.0.0",
    category: "prop",
    sizeMB: 44.1,
    updatedAt: "2025-09-14T08:00:00Z",
    status: "draft",
    usage: "promo",
    tags: ["brand", "event"],
    locations: 0,
  },
  {
    id: "a-004",
    name: "경복궁_담장",
    bundleKey: "gyeongbokgung/wall@4",
    version: "1.1.4",
    category: "wall",
    sizeMB: 128.6,
    updatedAt: "2025-09-08T09:00:00Z",
    status: "published",
    usage: "historical",
    tags: ["wall", "tile", "lod2"],
    locations: 12,
  },
  {
    id: "a-005",
    name: "브랜드_부스_프레임",
    bundleKey: "promo/booth_frame@7",
    version: "0.9.2",
    category: "prop",
    sizeMB: 63.3,
    updatedAt: "2025-09-10T12:00:00Z",
    status: "archived",
    usage: "promo",
    tags: ["kiosk", "demo"],
    locations: 0,
  },
];